### ISSUE TITLE
Incorrect highlighting for color if property value is multiline

### ISSUE THREAD

**Issue by hudochenkov** [P233/Syntax-highlighting-for-Sass#38]
``` css
span {
    box-shadow: 10px -1px 0 #fff,
                0 -1px 0 #fff,
                0 6px 0 #fff,
                10px 6px 0 #fff,
                10px 0 0 #fff;
}
```

![screen shot 2014-05-26 at 12 57 38](https://cloud.githubusercontent.com/assets/654597/3081231/6e20c264-e4bc-11e3-8305-3811abb8c8ec.png)
