### ISSUE TITLE
Empty url() is messing highlighting while looking for a closing bracket

### ISSUE THREAD

**Issue by pepelsbey** [P233/Syntax-highlighting-for-Sass#42]
Empty `url()` isn’t really valid, but my code shouldn’t jump and blink while I’m writing it. In `transform:scale()` everything is fine, `url()` is somehow special function.

``` scss
E {
    transform:scale();
    background:url();
    E {
        foo:bar;
        }
    }
E + E {
    transform:scale();
    }
```

![screen shot 2014-08-07 at 22 19 19](https://cloud.githubusercontent.com/assets/105274/3848463/272ba688-1e70-11e4-9b5f-104fac9035ab.png)
