### ISSUE TITLE
Space after colon is changing some functions look

### ISSUE THREAD

**Issue by pepelsbey** [P233/Syntax-highlighting-for-Sass#43]
`url()` in this case is again somehow different from transform functions.

``` scss
E {
    transform: scale(2) skew(50deg);
    transform: scale(2);

    transform:scale(2) skew(50deg);
    transform:scale(2);

    background: url(picture.png);
    background:url(picture.png);
    }
```

![screen shot 2014-08-07 at 22 25 48](https://cloud.githubusercontent.com/assets/105274/3848527/14d8e008-1e71-11e4-9f50-7765883b7682.png)
