### ISSUE TITLE
Weird scope found

### ISSUE THREAD

**Issue by mickimnet** [P233/Syntax-highlighting-for-Sass#7]
Hello everybody,

as I'm in the progress of adding highlighting in my color schemes ([Perv Color Scheme](https://github.com/FlavourSys/Perv-ColorScheme)) for your package, I found a very weird scope for the following code snippet:

``` scss
.content-navigation {
  border-color: $blue;
  color:
    darken($blue, 9%);
}
```

[ScopeHunter](https://github.com/facelessuser/ScopeHunter) tell's me, that the scope for `$blue` is:

```
source.scss meta.property-value.css.sass, support.constant.property-value.css.sass variable
```

I think the "," is an error--which leads to not being able to color the variable accordingly.

Take care,
Mick
